### ISSUE TITLE
Implement mptcp experient and find a bug

### ISSUE THREAD

**Issue by cjqing0925** [multipath-tcp/mptcp#23] opened 2013-12-19 06:55 UTC
Hi,
   I am Jianqing chen.In recently,I have implement mptcp experient and find a strange bug.I am not able to fix out,please help me.
#    The Bug phenomenon: the screen is black and no log. The keyboard and mouse have no reaction. The server is  on hook state.After I reboot the server ,and look up the /var/log/message,there is no valid message .

Dec 19 19:46:00 12007860 kernel: net/mptcp/mptcp_ctrl.c: mptcp_close: Close of meta_sk with tok 0xa1eb92c4
Dec 19 19:46:00 12007860 kernel: net/mptcp/mptcp_ctrl.c: mptcp_sock_destruct destroying meta-sk
Dec 19 19:46:05 12007860 kernel: net/mptcp/mptcp_ctrl.c: mptcp_alloc_mpcb: created mpcb with token 0xa6d58b76
Dec 19 19:46:05 12007860 kernel: net/mptcp/mptcp_ctrl.c: mptcp_select_ack_sock pi 1 state 3 last_dseq 0
Dec 19 19:46:05 12007860 kernel: net/mptcp/mptcp_ctrl.c: mptcp_select_ack_sock pi 1 state 3 last_dseq 0
Dec 19 19:46:06 12007860 kernel: net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0xa6d58b76 pi 2, src_addr:172.16.0.93:80 dst_addr:172.16.0.219:37469, cnt_subflows now 2
Dec 19 19:46:06 12007860 kernel: net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0xa6d58b76 pi 3, src_addr:172.16.0.232:80 dst_addr:172.16.0.226:44161, cnt_subflows now 3
Dec 19 19:46:06 12007860 kernel: net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0xa6d58b76 pi 4, src_addr:172.16.0.232:80 dst_addr:172.16.0.219:51016, cnt_subflows now 4
Dec 19 19:46:06 12007860 kernel: net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0xa6d58b76 pi 5, src_addr:172.16.0.233:80 dst_addr:172.16.0.226:33406, cnt_subflows now 5
Dec 19 19:46:06 12007860 kernel: net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0xa6d58b76 pi 6, src_addr:172.16.0.233:80 dst_addr:172.16.0.219:57595, cnt_subflows now 6
Dec 19 19:46:06 12007860 kernel: net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0xa6d58b76 pi 7, src_addr:172.16.0.234:80 dst_addr:172.16.0.226:59579, cnt_subflows now 7
Dec 19 19:46:06 12007860 kernel: net/mptcp/mptcp_ctrl.c: mptcp_add_sock: token 0xa6d58b76 pi 8, src_addr:172.16.0.234:80 dst_addr:172.16.0.219:52350, cnt_subflows now 8
Dec 19 21:48:21 12007860 syslogd 1.4.1: restart.
Dec 19 21:48:21 12007860 kernel: klogd 1.4.1, log source = /proc/kmsg started.
Dec 19 21:48:21 12007860 kernel: Linux version 3.11.3-002 (root@localhost.localdomain) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-1) (GCC) ) #21 SMP Wed Dec 18 11:12:50 CST 2013
Dec 19 21:48:21 12007860 kernel: Command line: ro root=LABEL=/ crashkernel=128M@32M
# Dec 19 21:48:21 12007860 kernel: e820: BIOS-provided physical RAM map:

  I set up the environment in LAN and the client have the dual cards, server have the four cards.There is establlishing eight flow.It no behind NAT.
##     Apache is built on the server, and the client continuously to download the data from Apache.But the above phenomenon is appear in  normal running a day.

The route table of server is 
[root@12007860 crash]# ip route show 
default via 172.16.0.254 dev eth0 
169.254.0.0/16 dev eth3  scope link 
172.16.0.0/24 dev eth0  proto kernel  scope link  src 172.16.0.93 
172.16.0.0/24 dev eth1  proto kernel  scope link  src 172.16.0.232 
172.16.0.0/24 dev eth2  proto kernel  scope link  src 172.16.0.233 
172.16.0.0/24 dev eth3  proto kernel  scope link  src 172.16.0.234 

[root@12007860 crash]# ifconfig
eth0      Link encap:Ethernet  HWaddr BC:30:5B:F6:0A:A4  
          inet addr:172.16.0.93  Bcast:172.16.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:23605 errors:0 dropped:330 overruns:0 frame:0
          TX packets:3275 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1845627 (1.7 MiB)  TX bytes:343220 (335.1 KiB)
          Memory:dcb00000-dcc00000 

eth1      Link encap:Ethernet  HWaddr BC:30:5B:F6:0A:A5  
          inet addr:172.16.0.232  Bcast:172.16.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:19768 errors:0 dropped:324 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1529734 (1.4 MiB)  TX bytes:84 (84.0 b)
          Memory:dcc00000-dcd00000 

eth2      Link encap:Ethernet  HWaddr BC:30:5B:F6:0A:A6  
          inet addr:172.16.0.233  Bcast:172.16.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:19943 errors:0 dropped:327 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1542151 (1.4 MiB)  TX bytes:84 (84.0 b)
          Memory:dcd00000-dce00000 

eth3      Link encap:Ethernet  HWaddr BC:30:5B:F6:0A:A7  
          inet addr:172.16.0.234  Bcast:172.16.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:19908 errors:0 dropped:326 overruns:0 frame:0
          TX packets:3 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1538760 (1.4 MiB)  TX bytes:126 (126.0 b)
          Memory:dce00000-dcf00000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

[root@12007860 crash]# uname -a
Linux 12007860 3.11.3-002 #21 SMP Wed Dec 18 11:12:50 CST 2013 x86_64 x86_64 x86_64 GNU/Linux

[root@12007860 crash]# sysctl -p
net.ipv4.ip_forward = 0
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.sysrq = 0
kernel.core_uses_pid = 0
net.ipv4.tcp_syncookies = 1
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_max_tw_buckets = 4000
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.ip_local_port_range = 10000 61000
net.mptcp.mptcp_enabled = 1
net.mptcp.mptcp_checksum = 0
net.mptcp.mptcp_path_manager = fullmesh
net.mptcp.mptcp_debug = 1

---

the route table of the client is 
[root@localhost ~]# ip route show
default via 172.16.0.254 dev eth0 
169.254.0.0/16 dev eth1  scope link 
172.16.0.0/24 dev eth0  proto kernel  scope link  src 172.16.0.226 
172.16.0.0/24 dev eth1  proto kernel  scope link  src 172.16.0.219 

[root@localhost ~]# ifconfig
eth0      Link encap:Ethernet  HWaddr 78:2B:CB:04:79:D2  
          inet addr:172.16.0.226  Bcast:172.16.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4737499049 errors:51 dropped:83200 overruns:0 frame:51
          TX packets:1066331153 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:7112109118772 (6.4 TiB)  TX bytes:72871035067 (67.8 GiB)

eth1      Link encap:Ethernet  HWaddr 78:2B:CB:04:79:D3  
          inet addr:172.16.0.219  Bcast:172.16.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4104173 errors:0 dropped:83227 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:591296406 (563.9 MiB)  TX bytes:128 (128.0 b)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:4474 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4474 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:443414 (433.0 KiB)  TX bytes:443414 (433.0 KiB)

[root@localhost ~]# uname -a
Linux localhost.localdomain 3.11.3-001 #17 SMP Fri Nov 29 17:13:42 CST 2013 x86_64 x86_64 x86_64 GNU/Linux

net.mptcp.mptcp_enabled = 1
net.mptcp.mptcp_checksum = 0
net.mptcp.mptcp_path_manager = fullmesh
## net.mptcp.mptcp_debug = 1

The version of multipath is v0.88.There is no useful information, I installed hung_task and start kdump on the server, but it does not have any panic information, just a black screen, keyboard and mouse have no reaction. The I had to manually restart.

Please help to find the problem, and then to guide me.Thanks!

Best Regards

**Comment by cpaasch** [comment] 2013-12-19 07:52
Hello,

we will need a crash-dump from the serial console to be able to fix this bug.
You can either monitor the serial console, or get a core-dump from the crash-kernel (have a look at https://wiki.ubuntu.com/Kernel/CrashdumpRecipe). The core-dump should then be at /var/crash/. And you would need to share this one.

Thanks!

**Comment by cjqing0925** [comment] 2013-12-19 09:05
Thank you for replying.
Yes,My system is Centos 5.8. I have installed kdump, which is to be able to get crashdump, but the machine dies only a black screen, keyboard and mouse have no reaction, and there is no crashdump in the /var/crash, only manually restart.
In normal state ,my kdump is running.and I start up hung task for deadlock.
###################################################################3
[root@12007860 ~]# service kdump status
Kdump is operational
[root@12007860 ~]# sysctl -a |grep hung
kernel.hung_task_check_count = 4194304
kernel.hung_task_panic = 1
kernel.hung_task_timeout_secs = 120
kernel.hung_task_warnings = 10
[root@12007860 ~]# 
-========================================================
my test shell is 
[root@localhost ~]# cat /tmp/while_test.sh 
#!/bin/sh
i=1
while ((1))
do
        echo "...$i..."
        echo 1 > /proc/sys/net/mptcp/mptcp_enabled
        echo "---200M------mptcp_enabled-----------`cat /proc/sys/net/mptcp/mptcp_enabled`"
        (time wget -q http://172.16.0.93/200M -O /dev/null) 2>>wget_mptcp_200M.time

```
sleep 2 

echo "...$i..."
    echo 0 > /proc/sys/net/mptcp/mptcp_enabled
    echo "---200M------mptcp_enabled-----------`cat /proc/sys/net/mptcp/mptcp_enabled`"
    (time wget -q http://172.16.0.93/200M -O /dev/null) 2>>wget_no_mptcp_200M.time

    sleep 2
    i=$(($i+1))
```

# done

**Comment by cpaasch** [comment] 2013-12-19 09:09
Can you check that the crashkernel is loaded with:

cat /sys/kernel/kexec_*

It should reboot the machine when the kernel crashes. However, on my Ubuntu it does not work either. This seems to be an upstream bug.

**Comment by cjqing0925** [comment] 2013-12-19 09:24
When other kernel occure panic, it will restart automatically, and the information will be stored in the /var/crash/vmcore, but this kernel  without any error, just a black screen. Now I put the other DEBUG options are compiled into the kernel, look to whether can appear useful information when crash.
################################################
[root@12007860 crash]# cat /sys/kernel/kexec_*
1
134217728
0
[root@12007860 crash]#

**Comment by cjqing0925** [comment] 2013-12-19 10:13
Now I compile  the softlockup_panic and hardlockup_panic options into the kernel for finding the deadlock.

**Comment by cpaasch** [comment] 2013-12-19 10:15
Yes, this may be the problem.

**Comment by cjqing0925** [comment] 2013-12-19 10:24
Now the server is running, and I am just waiting  for bug

**Comment by cjqing0925** [comment] 2013-12-25 07:09
Today I changed the script in order to  download resources quickly from server.
My LAN bandwidth is 110MB and the script is.
############################################
#!/bin/sh
i=1
while ((1))
do
        echo "...$i..."
        echo 1 > /proc/sys/net/mptcp/mptcp_enabled
        echo "---50M------mptcp_enabled-----------`cat /proc/sys/net/mptcp/mptcp_enabled`"
        (time wget -q http://172.16.0.93/50M -O /dev/null) 2>>wget_mptcp_50M.time
        i=$(($i+1))
done
############################################
I am sorry ,kdump is not normal  working when the panic occured,so I just offer the text
And the bug is [ffffffff8145c222] mptcp_write_xmit + 0x18b/0x4c8
##########################################
Through the tool of disassembly , I found the bug is from mptcp_write_xmit fuction,
#################################
ffffffff8145c097 <mptcp_write_xmit>:
......
ffffffff8145c20c:       e8 67 02 f7 ff          callq  ffffffff813cc478 <tcp_cwnd_test>
ffffffff8145c211:       85 c0                   test   %eax,%eax
ffffffff8145c213:       41 89 c7                mov    %eax,%r15d
ffffffff8145c216:       75 0e                   jne    ffffffff8145c226 <mptcp_write_xmit+0x18f>
ffffffff8145c218:       83 7d d4 ff             cmpl   $0xffffffffffffffff,0xffffffffffffffd4(%rbp)
ffffffff8145c21c:       0f 84 a6 02 00 00       je     ffffffff8145c4c8 <mptcp_write_xmit+0x431>
ffffffff8145c222:       0f 0b                   ud2a
ffffffff8145c224:       eb fe                   jmp    ffffffff8145c224 <mptcp_write_xmit+0x18d>
ffffffff8145c226:       83 7d d4 00             cmpl   $0x0,0xffffffffffffffd4(%rbp)
ffffffff8145c22a:       75 37                   jne    ffffffff8145c263 <mptcp_write_xmit+0x1cc>
ffffffff8145c22c:       8b 55 c4                mov    0xffffffffffffffc4(%rbp),%edx
#################################

int mptcp_write_xmit(struct sock *meta_sk, unsigned int mss_now, int nonagle, int push_one, gfp_t gfp)
{

---

```
cwnd_quota = tcp_cwnd_test(subtp, skb);
    if (!cwnd_quota) {
        /* May happen, if at the first selection we circumvented
         * the test due to a DATA_FIN (and got rejected at
         * tcp_snd_wnd_test), but the reinjected segment is not
         * a DATA_FIN.
         */
        BUG_ON(reinject != -1);//the bug from here!!!!
        break;
    }
```

---

}

**Comment by cpaasch** [comment] 2013-12-25 15:03
Hello,

do you still have the vmcore-file from /var/crash ?

**Comment by cjqing0925** [comment] 2013-12-27 05:50
After a week of work, I can get the bug of  vmcore finally . But the vmcore is about 7.9G, and how can I upload to you?

**Comment by cjqing0925** [comment] 2013-12-27 06:19
[  417.725666] ------------[ cut here ]------------
[  417.726230] kernel BUG at net/mptcp/mptcp_output.c:1153!
[  417.726786] invalid opcode: 0000 [#1] SMP 
[  417.727505] Modules linked in: autofs4 ipmi_devintf ipmi_si ipmi_msghandler be2iscsi iscsi_boot_sysfs ib_iser rdma_cm ib_cm iw_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp bnx2i cnic uio cxgb3i libcxgbi cxgb3 mdio libiscsi_tcp libiscsi scsi_transport_iscsi ext3 jbd dm_mirror dm_multipath scsi_dh video sbs sbshc battery ac mptcp_fullmesh parport_pc lp parport sg joydev dcdbas pcspkr wmi button tpm_tis rtc_cmos tpm tpm_bios igb i2c_algo_bit i2c_core ehci_pci dm_region_hash dm_log dm_mod ahci libahci libata shpchp megaraid_sas sd_mod scsi_mod ext4 jbd2 crc16 uhci_hcd ohci_hcd ehci_hcd [last unloaded: freq_table]
[  417.737453] CPU: 4 PID: 0 Comm: swapper/4 Tainted: P             3.11.3 #19
[  417.738010] Hardware name: Dell Inc. PowerEdge R620/036FVD, BIOS 1.4.8 10/25/2012
[  417.739019] task: ffff8801296fc3c0 ti: ffff8801296fe000 task.ti: ffff8801296fe000
[  417.740026] RIP: 0010:[<ffffffff8145c05e>]  [<ffffffff8145c05e>] mptcp_write_xmit+0x18b/0x4c8
[  417.741128] RSP: 0018:ffff88012a2039d8  EFLAGS: 00010213
[  417.741683] RAX: 0000000000000000 RBX: ffff8801274cf680 RCX: 0000000000000000
[  417.742239] RDX: 0000000000000010 RSI: 0000000000000000 RDI: ffff8802286cd2c0
[  417.742795] RBP: ffff88012a203a38 R08: ffff88012386b800 R09: 0000000000000578
[  417.743349] R10: ffff880128951140 R11: ffff88012a2038b8 R12: 0000000000010002
[  417.743905] R13: ffff8802286cd2c0 R14: ffff880126a2ad80 R15: 0000000000000000
[  417.744463] FS:  0000000000000000(0000) GS:ffff88012a200000(0000) knlGS:0000000000000000
[  417.745473] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  417.746025] CR2: ffffffffff600000 CR3: 00000001262ff000 CR4: 00000000000407e0
[  417.746667] Stack:
[  417.747208]  000000200000000e 0000000100000000 ffff8801238d3700 0000000200000002
[  417.748558]  0000057800000000 ffff88012526eb80 00000000291f1000 ffff880126a2ad80
[  417.749902]  ffff880126a2ad80 00000000000005b4 ffff88012879e140 0000000000000000
[  417.751248] Call Trace:
[  417.751794]  IRQ> 
[  417.751886] 
[  417.752514]  [ffffffff813ceffe>] tcp_write_xmit+0x53/0x3f8
[  417.753068]  [ffffffff813cf3cf>] __tcp_push_pending_frames+0x2c/0x88
[  417.753624]  [ffffffff8145bcea>] mptcp_write_space+0x35/0x39
[  417.754181]  [ffffffff813c8745>] tcp_check_space+0x14d/0x156
[  417.754737]  [ffffffff813cc186>] tcp_rcv_established+0x4c1/0x543
[  417.755293]  [ffffffff813d5363>] ? tcp_v4_rcv+0x543/0xaa2
[  417.755849]  [ffffffff813d3a40>] tcp_v4_do_rcv+0x21c/0x610
[  417.756405]  [ffffffff8147d09c>] ? _raw_spin_lock_nested+0x6a/0x73
[  417.756961]  [ffffffff813d53a3>] tcp_v4_rcv+0x583/0xaa2
[  417.757515]  [ffffffff813b3a29>] ? ip_local_deliver_finish+0x3e/0x3c1
[  417.758073]  [ffffffff813b3c43>] ip_local_deliver_finish+0x258/0x3c1
[  417.758629]  [ffffffff813b3a29>] ? ip_local_deliver_finish+0x3e/0x3c1
[  417.759185]  [ffffffff813b328f>] ip_local_deliver+0x73/0x7b
[  417.759739]  [ffffffff813b39d3>] ip_rcv_finish+0x58f/0x5a7
[  417.760291]  [ffffffff813b31dc>] ip_rcv+0x28c/0x2cc
[  417.760932]  [ffffffff8137c01a>] __netif_receive_skb_core+0x988/0xa53
[  417.761489]  [ffffffff8137b8f0>] ? __netif_receive_skb_core+0x25e/0xa53
[  417.762046]  [ffffffff8137c141>] __netif_receive_skb+0x5c/0x65
[  417.762602]  [ffffffff8137e384>] netif_receive_skb+0x1a8/0x1b3
[  417.763158]  [ffffffff8137ebb6>] napi_gro_receive+0x3b/0x78
[  417.763720]  [ffffffffa0207e6a>] igb_poll+0xae3/0xdab [igb]
[  417.764276]  [ffffffff81381b2d>] net_rx_action+0xbe/0x280
[  417.764832]  [ffffffff8103ff4f>] __do_softirq+0x180/0x359
[  417.765386]  [ffffffff8104049e>] irq_exit+0x54/0x62
[  417.765942]  [ffffffff81003371>] do_IRQ+0x9b/0xb2
[  417.766495]  [ffffffff8147d36f>] common_interrupt+0x6f/0x6f
[  417.767047]  EOI>
[  417.767138] 
[  417.767766]  [ffffffff8147ab3e>] ? __schedule+0x178/0xa54
[  417.768319]  [ffffffff8134ac9e>] ? cpuidle_enter_state+0x43/0xb0
[  417.768876]  [ffffffff8134aca2>] ? cpuidle_enter_state+0x47/0xb0
[  417.769433]  [ffffffff8134ac9e>] ? cpuidle_enter_state+0x43/0xb0
[  417.769990]  [ffffffff8134b0c6>] cpuidle_idle_call+0x190/0x2e5
[  417.770546]  [ffffffff81009e17>] arch_cpu_idle+0x9/0x1d
[  417.771101]  [ffffffff8107ec89>] cpu_startup_entry+0x225/0x2d8
[  417.771661]  [ffffffff810267aa] start_secondary+0x1c0/0x1c5
[  417.772213] Code: 41 0f b7 c4 85 c0 89 45 b8 75 04 0f 0b eb fe 48 89 de 4c 89 ef e8 67 02 f7 ff 85 c0 41 89 c7 75 0e 83 7d d4 ff 0f 84 a6 02 00 00 <0f> 0b eb fe 83 7d d4 00 75 37 8b 55 c4 48 89 de 4c 89 f7 e8 11 
[  417.779249] RIP  [ffffffff8145c05e>] mptcp_write_xmit+0x18b/0x4c8
[  417.779887]  RSP ffff88012a2039d8>

**Comment by cpaasch** [comment] 2013-12-27 12:31
I managed to reproduce the bug. It happens because your secondary interface has a different MTU than the one of the initial subflow and a DATA_FIN is combined with data.

I will let you know as soon as I have fixed it.

Cheers,
Christoph

**Comment by cpaasch** [comment] 2013-12-27 14:34
Fixed by:

commit a6625b68c6a1a9b841323871623068110f31b6a9
Author: Christoph Paasch christoph.paasch@uclouvain.be
Date:   Fri Dec 27 13:55:40 2013 +0100

```
mptcp: Fix Bug#23: Correctly handle congestion-window limitations

We may encounter cwnd-limitations after choosing a subflow, because we
change tso_segs afterwards. If this happens on a DATA_FIN with data, we
might reject this segment, if tso_segs becomes bigger than 1.

This patch fixes this, by correctly handling cwnd-limitations. If the
subflow is limited, we avoid reselecting this one and choose another
subflow.

Reported-by: cjqing0925 (https://github.com/cjqing0925)
Fixes: https://github.com/multipath-tcp/mptcp/issues/23
Signed-off-by: Christoph Paasch <christoph.paasch@uclouvain.be>
```

**Closed as completed by cpaasch** 2013-12-27 14:34 UTC
Labels: bug, Level: Critical

**Comment by cjqing0925** [comment] 2013-12-28 02:38
OK,I will test it. Thanks
