### ISSUE TITLE
Question: Can not capture FIN when mptcp subflow close

### ISSUE THREAD

**Issue by ldcanh** [multipath-tcp/mptcp#104] opened 2015-12-10 02:59 UTC
Hello All,

I am working on a project for monitoring statistics of all of mptcp
subflows as tx bytes, tx packets, rx bytes, rx packets. My program
runs on a computer (it runs on userspace, bypass kernel as dpdk for
getting better performance) to forward and capture mptcp subflows
statistics of two computers: MPTCP Client and MPTCP Server as bellow:
[MPTCP Client] <-----Switch----> [myprogram] <-----Switch----> [MPTCP Server]

My MPTCP kernel is version 0.89 build on Ubuntu 14.04.3 LTS. MPTCP
Client has two interface will connect with one interface on MPTCP
Server for testing. So one mptcp connection has two mptcp subflows.

For simple parsing packet, my program capture each subflow as normal
tcp: create a flow when receiving (SYN, SYN/ACK, ACK) and delete
flow when receiving FIN or RST from one of two directions.

Now I use idleconn and httperf for testing. Everything work ok when
test with 20K idle connections (= 40K mptcp subflows) and 10K active
 connection (= 20K mptcp subflows) with httperf (file 1Mb or 10Mb). My
program catch up perfectly with: Number subflows added then number
subflow deleted and number bytes, packets of each subflow (Same as 
sending from MPTCP Client and receiving from MPTCP Server).

When i use httperf with big file > 10Gb (number of idleconn and
httperf same as before), my program receiving number subflows added correctly
( I compare 60K subflows log is the same 60K subflows on MPTCP Server).
 But when I kill all process httperf and idleconn by command on MPTCP client: 
 "sudo killall httperf idleconn", my program can not catch all of FIN or RST of subflows, 
there are still ~10 subflows that my program can not receive FIN or RST.
When i check "ss -at | grep ..."  all connection closed on both of MPTCP Server and 
MPTCP Client.

The strange thing is sometime it can capture FIN ok (For example when
i run 10 time, there 2-3 times it work ok).  And running httperf
with small file, it executes and exits normally (Do not use kill), my
program also work ok. I don't understand why using kill on MPTCP
client can be affect to capture FIN or RST on my program. But when i run
with small connection 5K active connection httperf, it works ok event
if using kill.

On RFC 6824 part "3.3.3.  Closing a Connectionpage", page 30: " Once a
   DATA_FIN has been acknowledged, all remaining subflows MUST be
   closed with standard FIN exchanges.  Both hosts SHOULD send FINs on
   all subflows, as a courtesy to allow middleboxes to clean up state
   even if an individual subflow has failed.  It is also encouraged to
   reduce the timeouts (Maximum Segment Life) on subflows at end
   hosts."

So my question is why some mptcp subflows do not send FIN (or RST)
before close as tcp normal (RFC 6824 above)? (But all subflows were closed
on MPTCP Server and MPTCP client when verify with ss -at | grep ...)

And why kill httperf and idleconn affect sending FIN from MPTCP client? (when 
run with many connections)

Please help and give me some advices.

Many thanks,
Canh

**Comment by cpaasch** [comment] 2015-12-10 05:28
Killing the process might result in the sending of a RST. The reason why you might not see the RST on your process might be because the RST just got lost in the network.

Maybe you can share a packet-trace on client and server. Then we can see what exactly is going on.

**Comment by ldcanh** [comment] 2015-12-10 18:53
Thank you for your help.

As your advice, i make the test and give you more informations.
This is the scenario of test:

[MPTCP Client]           <-- Router --> [my program] <-- Router --> [MPTCP Server]
{xgbe0: 10.10.10.216}    ======================                {xgbe0: 10.10.30.214}
{xgbe1: 10.10.20.216}    ======================  

The step of testing:
1) On MPTCP Client, I run httperf with 10K connection = 20K subflows to
download a big file > 10Gb. The connections established:
    test01@MPTCP-Client:~/test_script/demo_test/214_test$ ss -at |grep 10.10.10 | wc -l
    10000
    test01@MPTCP-Client:~/test_script/demo_test/214_test$ ss -at |grep 10.10.20 | wc -l
    10000

2) On MPTCP Server, first i run 3 program tcpdump to capture SYN+ACK, FIN and RST as bellow:

2.1) test01@MPTCP-Server:~$ sudo tcpdump -n -vvv -i any tcp port 7683 and 'tcp[tcpflags] & (tcp-syn) != 0'  and  'tcp[tcpflags] & (tcp-ack) != 0' -w mptcp_s\
yn_ack.pcap
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 65535 bytes
^C20000 packets captured
20000 packets received by filter
0 packets dropped by kernel

2.2) test01@MPTCP-Server:~$ sudo tcpdump -n -vvv -i any tcp port 7683 and 'tcp[tcpflags] & (tcp-fin) != 0' -w mptcp_test_fin.pcap
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 65535 bytes
^C19592 packets captured
19592 packets received by filter
0 packets dropped by kernel

2.3) test01@MPTCP-Server:~$ sudo tcpdump -n -vvv -i any tcp port 7683 and 'tcp[tcpflags] & (tcp-rst) != 0' -w mptcp_test_rst.pcap
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 65535 bytes
^C72283 packets captured
72283 packets received by filter
0 packets dropped by kernel

3) On MPTCP Server, get all mptcp subflows with ESTABLISHED state and save to file:
test01@MPTCP-Client:~/test_script/demo_test/215_test$ ss -at |grep 10.10.10 | wc -l
10000
test01@MPTCP-Client:~/test_script/demo_test/215_test$ ss -at |grep 10.10.20 | wc -l
10000

test01@MPTCP-Server:~$ ss -at | grep 10.10.20 > mptcp_net_20.txt
test01@MPTCP-Server:~$ ss -at | grep 10.10.10 > mptcp_net_10.txt

4) On MPTCP Client, run: sudo killall httperf
Wait and we have the result of tcpdump as 2.2 and 2.3, here no packets dropped by kernel.

On MPTCP Server, there is not any subflows:
test01@MPTCP-Server:~$ ss -at | grep 10.10.10 | wc -l
0
test01@MPTCP-Server:~$ ss -at | grep 10.10.20 | wc -l
0

5) Check my program, i found two subflows that it can not receive FIN or RST:
   ('10.10.20.216', 43682, '10.10.30.214', 7683)
   ('10.10.20.216', 22150, '10.10.30.214', 7683)

6) Check two subflows in ESTABLISHED connections, it exists:
test01@MPTCP-Server:~$ grep 43682 mptcp_net_20.txt
ESTAB      0      0            10.10.30.214:7683          10.10.20.216:43682
test01@MPTCP-Server:~$ grep 22150 mptcp_net_20.txt
ESTAB      0      0            10.10.30.214:7683          10.10.20.216:22150

7) Check a subflow in tcpdump file:
   For example, here i check the subflow with port 43682:
- In file mptcp_syn_ack.pcap, it exist as image subflow_syn_ack.png
- In file mptcp_test_fin.pcap and mptcp_test_rst.pcap, this subfow does not exist,
   you can see the image subflow_fin.png or subflow_rst.png

So the conclusion, MPTCP Server does not receive FIN or RST of two
subflows as tcp normal. The problem occurs sometime, for example when i
run this test ~ 5 times, there is only one time it does receive FIN or
RST succesfully.

And my question: Why MPTCP Server does not receive FIN or RST of two
subflows but it still close all mptcp connections (and their subflows) successfully?

Is that right when mptcp connection receive a DATA_FIN, it wait
timeout and close subflows event if does not receive FIN or RST?

My program add subflows to list when receive SYN+ACK, and i want to capture RST or FIN to remove closed subflows. With the problem, It can not capture well. So i would like you give me some advice to know the subflow will close?

Sorry for my english and long text.

You can see all of files in attachment.

Thank you,
Canh
[mptcp_net_10.txt](https://github.com/multipath-tcp/mptcp/files/58542/mptcp_net_10.txt)
[mptcp_net_20.txt](https://github.com/multipath-tcp/mptcp/files/58543/mptcp_net_20.txt)

![subflow_fin](https://cloud.githubusercontent.com/assets/14865627/11724699/106cd74a-9fa8-11e5-966f-33eaf189d331.png)
![subflow_rst](https://cloud.githubusercontent.com/assets/14865627/11724701/108c6f92-9fa8-11e5-8255-e40132181032.png)
![subflow_syn_ack](https://cloud.githubusercontent.com/assets/14865627/11724702/108fa388-9fa8-11e5-98a5-bd9bf30b5560.png)
[mptcp_pcap.zip](https://github.com/multipath-tcp/mptcp/files/58549/mptcp_pcap.zip)

**Comment by cpaasch** [comment] 2015-12-13 21:00
Hmmm... Because you are killing the client which is downloading a file, the client will send a MP_FASTCLOSE, which will make the subflows get closed all through a RST. It may be that due to the high load, some of the subflows don't manage to send the RST (e.g., fail to allocate memory).
Can you show the output of `netstat -s -t` on client and server? This might shed more light. Please also show the output of `cat /proc/net/mptcp_net/snmp`.

**Comment by ldcanh** [comment] 2016-05-11 04:02
> Hmmm... Because you are killing the client which is downloading a file, the client will send a MP_FASTCLOSE, which will make the subflows get closed all through a RST. It may be that due to the high load, some of the subflows don't manage to send the RST (e.g., fail to allocate memory).

You are right. Thank you very much.

**Comment by cpaasch** [comment] 2016-09-11 00:47
Closing. Please reopen or ask on mptcp-dev if the issue is still there.

**Closed as completed by cpaasch** 2016-09-11 00:47 UTC
Labels: question
