### ISSUE TITLE
Available subflows aren't used anymore in long-lasting connections with kernel version 4

### ISSUE THREAD

**Issue by dweb32** [multipath-tcp/mptcp#273] opened 2018-07-18 13:16 UTC
I noticed a strange behaviour for larger file transfers / long-lasting MPTCP connections. At some point, the sender just stops using all available subflows and only sends over one path. In the end, the FIN is correctly send over all subflows again.

I did several experiments and was able to reproduce this problem with MPTCP releases based on the kernel version 4. Going back to 0.89, this strange effect disappears and all subflows are used as expected. This does not happen with smaller transfers, so you need to exceed a certain bandwidth-delay-product to be able to observe it.

### Experiment Setup
![setup_overview](https://user-images.githubusercontent.com/7917320/42880062-313d8734-8a93-11e8-88f6-dbbe9cdf00d5.png)

Both, sender and receiver are running the latest stable Debian 9 inside a virtual machine. They are directly connected over distinct VLANs. So there are no additional hops/routers in-between. Also there is no other traffic in the background that could cause congestion. The bandwidth (3, 6, 9 mbit/s) and delay (10, 7.6, 5 ms) is limited with netem. I prevent the creation of additional subflows by iptables. The MPTCP implementation was compiled from your git-repository, just to have the same code-base.

I send a 100 MB random text file from 192.168.11.3 to 192.168.11.4 via ftp in passive mode and capture the traffic at the server with tcpdump.

These settings are default settings for debian 9 and I have not changed them:
```
net.core.rmem_default = 229376
net.core.rmem_max = 229376
net.core.wmem_default = 229376
net.core.wmem_max = 229376
net.ipv4.tcp_rmem = 4096 87380 6291456
net.ipv4.tcp_wmem = 4096 16384 4194304
net.ipv4.tcp_windows_scaling = 1
```

I also kept the default settings for this example, but i was able to reproduces this behaviour with other experimental schedulers, too.
```
net.mptcp.mptcp_path_manager=fullmesh
net.mptcp.mptcp_scheduler=default
net.ipv4.tcp_congestion_control=cubic
net.ipv4.tcp_windows_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
```

### Plots
Here are some plots to illustrate the effect causing a performance degeneration. All measurements were performed within the same experiment setup.

**3 subflows with MPTCP checksum enabled:**
![tcpdump-any-1](https://user-images.githubusercontent.com/7917320/42873505-7211f7e0-8a7f-11e8-8451-2912fa3e4792.png)
![tcpdump-any-2](https://user-images.githubusercontent.com/7917320/42873514-7a40f36c-8a7f-11e8-98aa-246e7b65662b.png)

[tcpdump-any-1.zip](https://github.com/multipath-tcp/mptcp/files/2205827/tcpdump-any-1.zip)

_Note that the order and time of the stopping subflows is not constant. Also, only the fastest subflow keeps sending, even though we initiated the connection via the slower (red) underflow._

**2 subflows with MPTCP checksum enabled:**
![tcpdump-any-3](https://user-images.githubusercontent.com/7917320/42874652-ea8faada-8a81-11e8-9587-6a48d7949411.png)
![tcpdump-any-4](https://user-images.githubusercontent.com/7917320/42874607-d4920070-8a81-11e8-952a-8ad7f1346a20.png)
![tcpdump-any-6](https://user-images.githubusercontent.com/7917320/42874900-96bdfe4c-8a82-11e8-8c42-70180a051619.png)

_Note that this happens even for only two subflows._

**2 subflows without MPTCP checksum:**
![tcpdump-any-5](https://user-images.githubusercontent.com/7917320/42875008-dfcd3224-8a82-11e8-80af-5e67304be454.png)

Interestingly, without checksum it seams to work...
But if we extend the transfer time by reducing the bandwidth of the experiment setup, we can observe the same problem again. The longer transfer time just compensates the performance gain of the disabled checksum operation. I my experiments, the checksum operation reduced the performance by 20-25%.

![tcpdump-any-7](https://user-images.githubusercontent.com/7917320/42880850-0f9a8778-8a96-11e8-9f1a-f72b6b2936e9.png)

Maybe this problem is somehow related to #261 or #252

**Comment by GinesGarcia** [comment] 2018-07-18 13:25
Hi!
I'm facing the same issue but I'm still trying to reproduce it in a more consistent way. Could you try generating traffic with iperf?

Thanks in advance,
Ginés.

**Comment by cpaasch** [comment] 2018-07-18 13:39
I have the feeling there is something wrong with the checksum-generation on the sender-side when sequence numbers are wrapping around.

**Comment by dweb32** [comment] 2018-07-18 23:58
I am not sure if the checksum-generation itself causes the problem. Because I tested this with and without enabled checksum. But i had to either increase the file size or decrease the bandwidth to trigger this behavior.

**Comment by cpaasch** [comment] 2018-07-19 14:20
Do you see any logs on the receiver-side of ```mptcp_verif_dss_checksum``` ?

**Comment by dweb32** [comment] 2018-07-20 09:23
I repeated the experiment with enabled `net.mptcp.mptcp_debug=1` and used `iperf -c 192.168.11.4 -t 180` instead of `ftp` in order to generate traffic like @GinesGarcia is doing. Again i was able to reproduce the effect in a consistent way.

![tcpdump-iperf](https://user-images.githubusercontent.com/7917320/42994235-cc9499fe-8c0d-11e8-8ee3-5575ad32380d.png)
[tcpdump-iperf.zip](https://github.com/multipath-tcp/mptcp/files/2213257/tcpdump-iperf.zip)


What options are you using with iperf? Maybe you are just not exceeding the sequence number space. Anyway, I remember an ongoing discussion on iperf performance here #175.

@cpaasch, here is the `dmesg` output on the receiver-side:
```
[176082.773194] mptcp_address_worker could not find id
[176083.623540] device eth1 entered promiscuous mode
[176083.803465] device eth2 entered promiscuous mode
[176084.559848] mptcp_alloc_mpcb: created mpcb with token 0xebadbbbc
[176084.559890] mptcp_add_sock: token 0xebadbbbc pi 1, src_addr:192.168.11.4:5001 dst_addr:192.168.11.3:41958, cnt_subflows now 1
[176084.586092] mptcp_add_sock: token 0xebadbbbc pi 2, src_addr:192.168.12.4:5001 dst_addr:192.168.12.3:36159, cnt_subflows now 2
[176265.110802] device eth1 left promiscuous mode
[176265.114018] device eth2 left promiscuous mode
[176265.853746] mptcp_close: Close of meta_sk with tok 0xebadbbbc
[176265.874293] mptcp_del_sock: Removing subsock tok 0xebadbbbc pi:2 state 7 is_meta? 0
[176265.887655] mptcp_del_sock: Removing subsock tok 0xebadbbbc pi:1 state 7 is_meta? 0
[176265.887677] mptcp_sock_destruct destroying meta-sk token 0xebadbbbc
```


I ran the experiment a second time and enabled debug on the sending-side too:
[tcpdump-iperf-debug.zip](https://github.com/multipath-tcp/mptcp/files/2213279/tcpdump-iperf-debug.zip)
**sending-side**
```
[175191.594603] mptcp_address_worker could not find id
[175193.720881] mptcp_alloc_mpcb: created mpcb with token 0xe6e2fff3
[175193.720906] mptcp_add_sock: token 0xe6e2fff3 pi 1, src_addr:192.168.11.3:41960 dst_addr:192.168.11.4:5001, cnt_subflows now 1
[175193.742055] mptcp_add_sock: token 0xe6e2fff3 pi 2, src_addr:0.0.0.0:0 dst_addr:0.0.0.0:0, cnt_subflows now 2
[175193.742097] mptcp_init4_subsockets: token 0xe6e2fff3 pi 2 src_addr:192.168.12.3:0 dst_addr:192.168.11.4:5001 ifidx: 7
[175193.742174] mptcp_add_sock: token 0xe6e2fff3 pi 3, src_addr:0.0.0.0:0 dst_addr:0.0.0.0:0, cnt_subflows now 3
[175193.742241] mptcp_init4_subsockets: token 0xe6e2fff3 pi 3 src_addr:192.168.11.3:0 dst_addr:192.168.12.4:5001 ifidx: 5
[175193.742315] mptcp_add_sock: token 0xe6e2fff3 pi 4, src_addr:0.0.0.0:0 dst_addr:0.0.0.0:0, cnt_subflows now 4
[175193.742385] mptcp_init4_subsockets: token 0xe6e2fff3 pi 4 src_addr:192.168.12.3:0 dst_addr:192.168.12.4:5001 ifidx: 7
[175324.608047] mptcp_del_sock: Removing subsock tok 0xe6e2fff3 pi:3 state 7 is_meta? 0
[175324.608130] mptcp_del_sock: Removing subsock tok 0xe6e2fff3 pi:2 state 7 is_meta? 0
[175373.975092] mptcp_close: Close of meta_sk with tok 0xe6e2fff3
[175374.909560] mptcp_del_sock: Removing subsock tok 0xe6e2fff3 pi:4 state 7 is_meta? 0
[175374.918907] mptcp_del_sock: Removing subsock tok 0xe6e2fff3 pi:1 state 7 is_meta? 0
[175374.929114] mptcp_sock_destruct destroying meta-sk token 0xe6e2fff3
```
**receiver-side**
```
[178599.727632] mptcp_address_worker could not find id
[178600.469622] device eth1 entered promiscuous mode
[178600.625645] device eth2 entered promiscuous mode
[178601.262113] mptcp_alloc_mpcb: created mpcb with token 0xf98d9e5
[178601.262138] mptcp_add_sock: token 0xf98d9e5 pi 1, src_addr:192.168.11.4:5001 dst_addr:192.168.11.3:41960, cnt_subflows now 1
[178601.288744] mptcp_add_sock: token 0xf98d9e5 pi 2, src_addr:192.168.12.4:5001 dst_addr:192.168.12.3:39751, cnt_subflows now 2
[178781.695651] device eth1 left promiscuous mode
[178781.698893] device eth2 left promiscuous mode
[178782.425009] mptcp_close: Close of meta_sk with tok 0xf98d9e5
[178782.445523] mptcp_del_sock: Removing subsock tok 0xf98d9e5 pi:2 state 7 is_meta? 0
[178782.460003] mptcp_del_sock: Removing subsock tok 0xf98d9e5 pi:1 state 7 is_meta? 0
[178782.460024] mptcp_sock_destruct destroying meta-sk token 0xf98d9e5
```

**Comment by cpaasch** [comment] 2018-07-26 18:08
Ok - no DSS-checksum failures...

**Comment by cpaasch** [comment] 2018-07-26 20:11
@s6dlwebe:
Is the Netem limitation done on the sender host? (that's what it seems like by looking at the packet-traces)

Doing that, results in weird behavior, because you will get backpressure from netem up to the MPTCP-stack. If you configure the netem rules on a intermediate router, I think your results will look different.

**Comment by dweb32** [comment] 2018-07-26 20:29
Yes, you are right. The limitations are done on the sender host. I will change the evaluation setup and try again. But I am still wondering why I do not see this when using MPTCP v0.89.5 within the same setup.

**Comment by cpaasch** [comment] 2018-07-26 21:08
On v0.89.5, there wasn't yet TCP Small-queues implemented. TSQ limits the number of bytes queued in the stack (https://lwn.net/Articles/507065/). When you put netem locally (which is going to add more to the queueing), you will artificially keep the congestion-window low.

I am closing this issue here. If the problem persists, please reopen or file a new issue. Thanks!

**Closed as completed by cpaasch** 2018-07-26 21:08 UTC
Labels: bug, Level: Critical

**Comment by AlexanderFroemmgen** [comment] 2018-07-30 19:46
Should we add a simple Mininet setup to the webpage to avoid these issues in the future? I had similar expieriences a few months ago (http://progmp.net/mininetPitfalls.html)

**Comment by cpaasch** [comment] 2018-08-01 17:51
@AlexanderFroemmgen  - yes, that would be awesome! Can you provide one?

**Comment by AlexanderFroemmgen** [comment] 2018-08-04 07:24
Sure. I will provide some scripts in a few days.
