### ISSUE TITLE
mptcp-trunk: net/ipv4/tcp_input.c wrong paste?

### ISSUE THREAD

**Issue by okias** [multipath-tcp/mptcp#24] opened 2013-12-30 23:13 UTC
This piece code look really suspicious. In mptcp_v0.88 it look OK.
                if (!sock_flag(sk, SOCK_DEAD)) {
                        /\* Wake up lingering close() */
                        sk->sk_state_change(sk);
                        break;
                case TCP_CLOSE:
                        if (tp->mp_killed)
                                goto discard;
                }

**Comment by furkanmustafa** [comment] 2013-12-30 23:16
Here it is; even in v0.88
https://github.com/multipath-tcp/mptcp/blob/mptcp_v0.88/net/ipv4/tcp_input.c#L5899

And I am having strange panic after successful transmission (when session ends), see panic log:
http://pastie.org/pastes/8587760/text?key=wzx1xlffxnohgnzsofobw

Thinking that this might be related

**Comment by cpaasch** [comment] 2013-12-31 09:28
@okias Nice catch! Will fix it.
@furkanmustafa Are you using mptcp_v0.88 or mptcp_trunk? Also, please submit a separate bug-report to not mix things up with David's catch.

**Comment by cpaasch** [comment] 2013-12-31 10:12
Fixed by:

commit e85fc77779df848a839713cd5f5e3fccbc006065
Author: Christoph Paasch christoph.paasch@uclouvain.be
Date:   Tue Dec 31 10:29:12 2013 +0100

```
mptcp: Fix Bug#24: Correctly handle closed-sockets in tcp_rcv_state_process

While merging to 3.11, we messed up one case-statement of the switch in
tcp_rcv_state_process. This patch moves the case-statement again where
it belongs.

Reported-by: David Heidelberger <david.heidelberger@ixit.cz>
Signed-off-by: Christoph Paasch <christoph.paasch@uclouvain.be>
```

**Closed as completed by cpaasch** 2013-12-31 10:12 UTC

**Comment by furkanmustafa** [comment] 2013-12-31 10:28
We were investigating it together, thinking that my panic might be related, since it was happening when the session is closing. Also my tree is slightly modified 3.13 for arm7 (beaglebone black), including mptcp modifications, so might be caused by something in my changes. Only posted here for the chance of this causing the panic.

If you see the logs, panic happens after successful mptcp connection (iperf -c multipath-tcp.org). it looks like it went through the closing/releasing code, and found the socket buffer already released, skbuff.h has a catch for the case it's already released, BUG()..

If you say it's probably not related, I will keep trying until I can find the source of that the problem and come back with a fix if related. Thanks.

**Comment by cpaasch** [comment] 2013-12-31 10:49
Ok, I see...

You probably should merge to 3.13-rc from mptcp_trunk (which is currently based on 3.12).
I guess you need the patch https://github.com/multipath-tcp/mptcp/commit/0fa5de4275d8055bdae9c19d9843a6b1800b2373 .

If you wait 2-3 weeks until 3.13 is out, I will merge mptcp_trunk with 3.13 and you can thus take this one.

**Comment by okias** [comment] 2013-12-31 11:45
It was @furkanmustafa catch on IRC. I just filled bug.

Anyway there is already few people on #mptcp IRC ;) If you want, you may join time to time :)

**Comment by furkanmustafa** [comment] 2013-12-31 14:55
Yes, your patch looks like fixed the issue, now i have running v3.13 for armv7/beaglebone-black, having mptcp.

Debug results from tests in the link below. looks like everything is fine. either https://github.com/multipath-tcp/mptcp/commit/e85fc77779df848a839713cd5f5e3fccbc006065 or https://github.com/multipath-tcp/mptcp/commit/0fa5de4275d8055bdae9c19d9843a6b1800b2373 fixed it, probably the second one.

Debug result:
http://pastie.org/pastes/8589712/text?key=nigzgyh92enc5feb93f3uq

**Comment by okias** [comment] 2013-12-31 15:07
P.S. @cpaasch could you push it too mptcp-trunk?

**Comment by cpaasch** [comment] 2014-01-02 08:21
@okias It's now in mptcp_trunk.

Cheers,
Christoph
