### ISSUE TITLE
V0.88 kernel-3.11.3   BUG: unable to handle kernel NULL pointer dereference at 0000000000000014

### ISSUE THREAD

**Issue by cjqing0925** [multipath-tcp/mptcp#28] opened 2014-02-23 13:28 UTC
[ 2465.647829] TCP: mptcp_fallback_infinite 0x462ef097 will fallback - pi 1, src 122.228.228.223 dst 220.181.112.207 from tcp_rcv_established+0x439/0x543
[ 5342.803548] perf samples too long (5007 > 5000), lowering kernel.perf_event_max_sample_rate to 25000
[ 8588.902154] device eth0 entered promiscuous mode
[ 8593.551460] device eth0 left promiscuous mode
[ 8605.082309] device eth1 entered promiscuous mode
[ 8606.025251] device eth1 left promiscuous mode
[ 8655.332253] device eth0 entered promiscuous mode
[ 8656.104308] device eth0 left promiscuous mode
[22277.587875] BUG: unable to handle kernel NULL pointer dereference at 0000000000000014
[22277.588588] IP: [<ffffffff814537af>] mptcp_reqsk_find_tk+0x73/0x83
[22277.588960] PGD 0 
[22277.589310] Oops: 0000 [#1] SMP 
[22277.589667] Modules linked in: xt_TCPMSS xt_tcpudp iptable_mangle ip_tables x_tables autofs4 ipmi_devintf ipmi_si ipmi_msghandler cpufreq_ondemand be2iscsi iscsi_boot_sysfs ib_iser rdma_cm ib_cm iw_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp bnx2i cnic uio cxgb3i libcxgbi cxgb3 mdio libiscsi_tcp libiscsi scsi_transport_iscsi ext3 jbd dm_mirror dm_multipath scsi_dh video sbs sbshc battery ac mptcp_fullmesh tcp_cubic parport_pc lp parport sg pcspkr igb i2c_algo_bit i2c_core serio_raw button tpm_tis tpm tpm_bios rtc_cmos i7core_edac ehci_pci edac_core acpi_cpufreq freq_table mperf dm_region_hash dm_log dm_mod ahci libahci libata cciss shpchp hpsa sd_mod scsi_mod ext4 jbd2 crc16 uhci_hcd ohci_hcd ehci_hcd [last unloaded: microcode]
[22277.593543] CPU: 6 PID: 0 Comm: swapper/6 Tainted: P             3.11.3 #25
[22277.593902] Hardware name: HP ProLiant DL160 G6  , BIOS O33 02/01/2012
[22277.594262] task: ffff880625926440 ti: ffff880625928000 task.ti: ffff880625928000
[22277.594949] RIP: 0010:[<ffffffff814537af>]  [<ffffffff814537af>] mptcp_reqsk_find_tk+0x73/0x83
[22277.595631] RSP: 0018:ffff880c3e6037a8  EFLAGS: 00010246
[22277.595982] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 00000000110bb7ac
[22277.596333] RDX: ffff880c3e60377c RSI: 00000000f77447d7 RDI: 00000000383f1ffe
[22277.596687] RBP: ffff880c3e6037b8 R08: 000000009fac8640 R09: 0000000052583c62
[22277.597042] R10: 0000000071b68f3c R11: 00000000ab7c7690 R12: 00000000383f1ffe
[22277.597403] R13: ffff880c3e603828 R14: 0000000000000000 R15: ffff880c16e590c0
[22277.597764] FS:  0000000000000000(0000) GS:ffff880c3e600000(0000) knlGS:0000000000000000
[22277.598448] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[22277.598803] CR2: 0000000000000014 CR3: 00000006080dd000 CR4: 00000000000007e0
[22277.599156] Stack:
[22277.607685]  ffff880c22c3ff00 ffff880c16e590c0 ffff880c3e6037e8 ffffffff81456ef8
[22277.608394]  ffffffff81456df5 ffff880c16e590e8 ffff880c3e603828 ffff880c22c3ff00
[22277.609103]  ffff880c3e603938 ffffffff813d5c74 ffff880c250b38a0 ffff880c20740040
[22277.609813] Call Trace:
[22277.610156]  <IRQ> 
[22277.610169] 
[22277.610518]  [<ffffffff81456ef8>] mptcp_reqsk_new_mptcp+0x103/0x1db
[22277.610874]  [<ffffffff81456df5>] ? mptcp_reqsk_destructor+0x1af/0x1af
[22277.611236]  [<ffffffff813d5c74>] tcp_v4_conn_request+0x3b2/0xbec
[22277.611588]  [<ffffffff8147c640>] ? _raw_spin_lock+0x6c/0x75
[22277.611945]  [<ffffffff81089818>] ? trace_hardirqs_on+0xd/0xf
[22277.612304]  [<ffffffff81040c64>] ? local_bh_enable+0xb2/0xba
[22277.612659]  [<ffffffff8138452b>] ? dev_queue_xmit+0x6fe/0x76f
[22277.613008]  [<ffffffff81383e2d>] ? dev_add_pack+0x56/0x56
[22277.613356]  [<ffffffff813ba221>] ? ip_finish_output+0x5da/0x659
[22277.613703]  [<ffffffff813b9f00>] ? ip_finish_output+0x2b9/0x659
[22277.614061]  [<ffffffff814469ce>] tcp_v6_conn_request+0x48/0x66d
[22277.614414]  [<ffffffff813f5eef>] ? check_leaf+0x98/0x22b
[22277.614769]  [<ffffffff813f8f43>] ? fib_table_lookup+0x460/0x480
[22277.615129]  [<ffffffff813caf1f>] tcp_rcv_state_process+0x80/0xe26
[22277.615485]  [<ffffffff813bd041>] ? __inet_lookup_established+0x37a/0x39b
[22277.615844]  [<ffffffff813bccc7>] ? __inet_check_established+0x29e/0x29e
[22277.616206]  [<ffffffff813d3791>] ? tcp_v4_hnd_req+0x101/0x194
[22277.616564]  [<ffffffff813d537b>] ? tcp_v4_rcv+0x55b/0xaa2
[22277.616916]  [<ffffffff813d3dc2>] tcp_v4_do_rcv+0x59e/0x610
[22277.617266]  [<ffffffff8147d07c>] ? _raw_spin_lock_nested+0x6a/0x73
[22277.617614]  [<ffffffff813d53a3>] tcp_v4_rcv+0x583/0xaa2
[22277.617962]  [<ffffffff813b3a29>] ? ip_local_deliver_finish+0x3e/0x3c1
[22277.618316]  [<ffffffff813b3c43>] ip_local_deliver_finish+0x258/0x3c1
[22277.618664]  [<ffffffff813b3a29>] ? ip_local_deliver_finish+0x3e/0x3c1
[22277.619019]  [<ffffffff813b328f>] ip_local_deliver+0x73/0x7b
[22277.619374]  [<ffffffff813b39d3>] ip_rcv_finish+0x58f/0x5a7
[22277.619726]  [<ffffffff813b31dc>] ip_rcv+0x28c/0x2cc
[22277.620082]  [<ffffffff8137c01a>] __netif_receive_skb_core+0x988/0xa53
[22277.620436]  [<ffffffff8137b8f0>] ? __netif_receive_skb_core+0x25e/0xa53
[22277.620784]  [<ffffffff8137c141>] __netif_receive_skb+0x5c/0x65
[22277.621129]  [<ffffffff8137e384>] netif_receive_skb+0x1a8/0x1b3
[22277.621474]  [<ffffffff8137ebb6>] napi_gro_receive+0x3b/0x78
[22277.621828]  [<ffffffffa025ee6a>] igb_poll+0xae3/0xdab [igb]
[22277.622180]  [<ffffffff81381b2d>] net_rx_action+0xbe/0x280
[22277.622532]  [<ffffffff8103ff4f>] __do_softirq+0x180/0x359
[22277.622887]  [<ffffffff8104049e>] irq_exit+0x54/0x62
[22277.623246]  [<ffffffff81003371>] do_IRQ+0x9b/0xb2
[22277.623603]  [<ffffffff8147d36f>] common_interrupt+0x6f/0x6f
[22277.623957]  <EOI> 
[22277.623970] 
[22277.624316]  [<ffffffff8134ac9e>] ? cpuidle_enter_state+0x43/0xb0
[22277.624671]  [<ffffffff8134aca2>] ? cpuidle_enter_state+0x47/0xb0
[22277.625029]  [<ffffffff8134ac9e>] ? cpuidle_enter_state+0x43/0xb0
[22277.625388]  [<ffffffff8134b0c6>] cpuidle_idle_call+0x190/0x2e5
[22277.625748]  [<ffffffff81009e17>] arch_cpu_idle+0x9/0x1d
[22277.626098]  [<ffffffff8107ec89>] cpu_startup_entry+0x225/0x2d8
[22277.626447]  [<ffffffff810267aa>] start_secondary+0x1c0/0x1c5
[22277.626792] Code: 74 1e e8 b0 4f c6 ff 85 c0 75 15 e8 db 4f c6 ff 84 c0 74 0c 48 c7 c7 80 64 a3 81 e8 ac 3f c3 ff 48 89 d8 a8 01 74 04 31 c0 eb 0b <44> 3b 63 14 75 b3 b8 01 00 00 00 5b 41 5c c9 c3 55 48 8b 97 90 
[22277.628158] RIP  [<ffffffff814537af>] mptcp_reqsk_find_tk+0x73/0x83
[22277.628517]  RSP <ffff880c3e6037a8>
[22277.628863] CR2: 0000000000000014
crash>

**Comment by cpaasch** [comment] 2014-02-23 19:09
Duplicate of #27

**Closed as completed** 2014-03-03 17:00 UTC
