### ISSUE TITLE
Question: About flood

### ISSUE THREAD

**Issue by self20** [multipath-tcp/mptcp#111] opened 2016-03-04 15:31 UTC
Good afternoon.

I was testing this kernel of which I spoke very well and the test was done on a dedicated server.

Now the server has been suspended by flood and has been since use this kernel.

I have this configuration:

net.mptcp.mptcp_enabled=1
net.mptcp.mptcp_checksum=0
net.mptcp.mptcp_ndiffports=2
net.mptcp.mptcp_syn_retries=1

Someone could tell me if there is something wrong with those lines? Server usage is seedbox for private trackers.

This configuration may be the cause? The server is 1 Gbit, there is perhaps a better configuration that avoids the flood?

Thank you very much, and great job! ;)

Cheers

**Comment by cpaasch** [comment] 2016-03-05 21:55
Can you clarify what you mean with "the server has been suspended by flood" ?

Thanks!

**Comment by mshary** [comment] 2016-03-29 21:39
Why did you turn off checksum? Also using fullmesh for a seedbox may yield better results then ndiffports in event of a DOS attack.

Here are some settings which may optimize mptcp,

net.mptcp.mptcp_checksum = 1
net.mptcp.mptcp_debug = 0
net.mptcp.mptcp_enabled = 1
net.mptcp.mptcp_path_manager = fullmesh
net.mptcp.mptcp_scheduler = default
net.mptcp.mptcp_syn_retries = 2

There are plenty of articles on internet on how to deal with TCP flood attack by settings various sysctl flags for TCP.

You may try,

net.ipv4.conf.default.rp_filter=1
net.ipv4.conf.all.rp_filter=1

net.ipv4.conf.all.send_redirects = 0
net.ipv4.tcp_syncookies=1
net.ipv4.tcp_rfc1337 = 1

Read the default sysctl.conf in your distro for more info regarding these flags.

Thank you.

**Comment by cpaasch** [comment] 2016-09-11 00:46
Closing. Please reopen or ask on mptcp-dev if the issue is still there.

**Closed as completed by cpaasch** 2016-09-11 00:46 UTC
Labels: question
